load(
    "@buck2-haskell//:defs.bzl",
    "haskell_binary",
    "haskell_library",
)
load(":wrap_cxx.bzl", "wrap_cxx")

native.cxx_library(
    name = "clib_cxx",
    srcs = ["cbits/clib.c"],
    headers = ["cbits/clib.h"],
    preferred_linkage = "shared",
    visibility = ["PUBLIC"],
)

wrap_cxx(
    name = "clib",
    wrapped = ":clib_cxx",
)

haskell_library(
    name = "libA",
    srcs = [
        "src/A.hs",
    ],
    strip_prefix = ["src"],
    visibility = ["PUBLIC"],
    deps = [
        "//tests:base",
    ],
    extra_libraries = [":clib"],
    allow_worker = True,
    _worker = "toolchains//:persistent_worker",
)

haskell_library(
    name = "libB",
    srcs = [
        "src/B.hs",
    ],
    strip_prefix = ["src"],
    visibility = ["PUBLIC"],
    deps = [
        "//tests:base",
        ":libA",
    ],
    allow_worker = True,
    _worker = "toolchains//:persistent_worker",
)

haskell_binary(
    name = "test1",
    srcs = ["app/test1.hs"],
    strip_prefix = ["app"],
    visibility = ["PUBLIC"],
    deps = [
        "//tests:base",
        ":libB",
    ],
    allow_worker = True,
    _worker = "toolchains//:persistent_worker",
)

sh_test(
    name = "test1_in_proj_ffi",
    test = ":test1"
)

#
# transitive in-project C deps
#

native.cxx_library(
    name = "clib_2_cxx",
    srcs = ["cbits/clib_2.c"],
    headers = ["cbits/clib_2.h"],
    preferred_linkage = "shared",
    visibility = ["PUBLIC"],
    exported_deps = [":clib_cxx"],
)

wrap_cxx(
    name = "clib_2",
    wrapped = ":clib_2_cxx",
)

haskell_library(
    name = "libC",
    srcs = [
        "src/C.hs",
    ],
    strip_prefix = ["src"],
    visibility = ["PUBLIC"],
    deps = [
        "//tests:base",
    ],
    extra_libraries = [":clib_2"],
    allow_worker = True,
    _worker = "toolchains//:persistent_worker",
)

haskell_library(
    name = "libD",
    srcs = [
        "src/D.hs",
    ],
    strip_prefix = ["src"],
    visibility = ["PUBLIC"],
    deps = [
        "//tests:base",
        ":libC",
    ],
    allow_worker = True,
    _worker = "toolchains//:persistent_worker",
)

haskell_binary(
    name = "test2",
    srcs = ["app/test2.hs"],
    strip_prefix = ["app"],
    visibility = ["PUBLIC"],
    deps = [
        "//tests:base",
        ":libD",
    ],
    allow_worker = True,
    _worker = "toolchains//:persistent_worker",
)

sh_test(
    name = "test2_in_proj_ffi",
    test = ":test2"
)
