load(
    "@buck2-haskell//:defs.bzl",
    "haskell_binary",
    "haskell_library",
)

haskell_library(
    name = "pkgA",
    srcs = ["A.hs"],
    deps = ["//tests:base"],
    allow_worker = False,
)

haskell_binary(
    name = "app",
    srcs = ["app.hs"],
    deps = [
        ":pkgA",
        "//tests:base",
    ],
    link_style = "static_pic",
    link_haskell_objects_at_once = True,
    allow_worker = False,
)

sh_test(
    name = "test_app",
    test = ":app",
)
